id: 25
title: '[meta] list of allowed options for `state`, `type`, `assignee`'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T11:04:11Z
updated: 2025-12-24T15:38:30Z
