_version: 1
id: 46
title: '[test] add automated tests for show command'
state: active
type: task
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2026-01-08T22:10:36Z
updated: 2026-01-14T21:44:21Z
