_version: 1
id: 59
title: '[cmd/show] remove title from metadata table'
state: new
type: ''
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-27T20:35:19Z
updated: 2026-01-27T20:35:19Z
