_version: 1
id: 55
title: '[cmd/show] prettify formatting of metadata markdown table'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-13T21:21:49Z
updated: 2026-01-13T21:21:49Z
