id: 52
title: '[test] add automated tests for id generation'
state: new
type: task
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-09T22:36:54Z
updated: 2026-01-09T22:36:54Z
