id: 15
title: '[cmd] modification on meta field `labels` could be harmonized'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:21:21Z
updated: 2025-12-23T12:26:24Z
