_version: 1
id: 16
title: '[cmd] improve workflow for show and edit ?'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:24:16Z
updated: 2025-12-26T19:50:53Z
