_version: 1
id: 11
title: '[cmd] add commands to edit meta fields `title`, `type` `labels`, `assignee`'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-22T19:18:29Z
updated: 2025-12-22T21:06:20Z
