id: 45
title: '[test] add automated tests for edit command'
state: new
type: task
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-08T22:10:34Z
updated: 2026-01-08T22:10:34Z
