id: 19
title: '[meta] add code relationship field ?'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:35:07Z
updated: 2025-12-28T17:07:29Z
