id: 41
title: '[cmd] do we need a command to show the history of an issue ?'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships:
  related: []
created: 2026-01-04T15:00:13Z
updated: 2026-01-04T15:00:13Z
