_version: 1
id: 18
title: '[meta] add issue relationship field(s)'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 29
created: 2025-12-23T10:30:22Z
updated: 2025-12-26T19:54:28Z
