id: 30
title: '[meta] add `reporter` field'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 31
created: 2025-12-27T12:22:57Z
updated: 2025-12-27T15:10:15Z
