_version: 1
id: 23
title: '[cmd/list] make default columns configurable'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:50:12Z
updated: 2025-12-23T18:15:11Z
