_version: 1
id: 57
title: '[cmd/list] allow filtering for ''me'' on assignee/reporter'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2026-01-14T22:53:37Z
updated: 2026-01-20T19:52:44Z
