id: 54
title: '[cmd/list] add possibility to filter on description.md'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-13T19:58:51Z
updated: 2026-01-13T19:58:51Z
