id: 10
title: '[cmd] add `search` command'
state: active
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 3
created: 2025-12-22T19:15:18Z
updated: 2026-01-12T20:39:14Z
