id: 10
title: '[cmd] add `search` command'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships:
  related:
  - 3
created: 2025-12-22T19:15:18Z
updated: 2025-12-22T19:15:18Z
