_version: 1
id: 17
title: '[structure] add possibility for discussions/comments ?'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:26:33Z
updated: 2025-12-23T10:26:33Z
