id: 48
title: '[cli] colorized output'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-09T16:24:40Z
updated: 2026-01-09T16:24:40Z
