_version: 1
id: 48
title: '[cmd/list] formatting: colorized output'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 49
  - 50
created: 2026-01-09T16:24:40Z
updated: 2026-01-09T21:31:12Z
