id: 50
title: '[cmd/list] formatting: dashed line between headers and values'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships:
  related:
  - 49
created: 2026-01-09T16:33:08Z
updated: 2026-01-09T16:34:35Z
