id: 50
title: '[cmd/list] formatting: dashed line between headers and values'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 49
  - 48
created: 2026-01-09T16:33:08Z
updated: 2026-01-09T21:30:44Z
