id: 51
title: '[cli] only executable from root'
state: new
type: bug
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-09T21:40:31Z
updated: 2026-01-09T21:40:31Z
