id: 37
title: '[cli] improve error messages for invalid options'
state: active
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2026-01-04T14:00:39Z
updated: 2026-01-11T20:46:29Z
