id: 12
title: '[cmd/show] improve representation'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-22T19:20:52Z
updated: 2025-12-23T12:26:25Z
