_version: 1
id: 6
title: '[id] add possibility to change how ID numbers are generated'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-22T12:58:47Z
updated: 2025-12-28T14:09:08Z
