_version: 1
id: 9
title: '[description] add a MD template for the issue description'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-22T16:45:01Z
updated: 2025-12-22T16:49:39Z
