_version: 1
id: 31
title: '[config] distinguish between version-controlled project configuration and local settings'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 30
created: 2025-12-27T13:04:09Z
updated: 2025-12-27T13:57:35Z
