id: 35
title: '[meta] possibility for empty priority'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-29T00:12:18Z
updated: 2025-12-29T01:23:20Z
