_version: 1
id: 42
title: '[cmd/new] bug: explicitly empty labels not handled correctly'
state: resolved
type: bug
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2026-01-06T21:44:46Z
updated: 2026-01-06T22:34:38Z
