id: 53
title: '[config] need a way to separately create settings.yaml'
state: resolved
type: bug
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2026-01-11T18:47:13Z
updated: 2026-01-11T19:32:47Z
