_version: 1
id: 3
title: '[cmd/list] add possibility to filter issues'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 10
created: 2025-12-22T12:46:56Z
updated: 2025-12-26T21:29:26Z
