id: 40
title: '[meta] add milestone/sprint/release field(s) ?'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-04T14:40:24Z
updated: 2026-01-04T14:40:24Z
