id: 49
title: '[cmd/list] formatting: bold headers'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships:
  related:
  - 50
  - 48
created: 2026-01-09T16:28:33Z
updated: 2026-01-09T21:30:44Z
