id: 49
title: '[cmd/list] formatting: bold headers'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2026-01-09T16:28:33Z
updated: 2026-01-09T16:28:33Z
