id: 13
title: '[cmd] add a command to remove label'
state: resolved
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-22T21:45:42Z
updated: 2025-12-22T23:39:19Z
