_version: 1
id: 21
title: '[git] staging should be more narrow'
state: active
type: feature
labels: []
reporter: t.burkard
assignee: t.burkard
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:37:47Z
updated: 2026-01-13T21:32:34Z
