_version: 1
id: 21
title: '[git] staging should be more narrow'
state: new
type: feature
labels: []
reporter: t.burkard
assignee: ''
priority: ''
due_date: ''
relationships: {}
created: 2025-12-23T10:37:47Z
updated: 2025-12-23T10:37:47Z
